### ISSUE TITLE
Configurable header and Firecheckout

### ISSUE THREAD

**Issue by bohdanchumak** [swissup/module-theme-editor#6]
Configurable header doesn't work properly with any Firecheckout page layout except full layout - it results in moving the header to the bottom of the page.

**Comment by vovayatsyuk** [comment]
The same behavior exists on the standard checkout page and any other page with empty layout:

![image](https://user-images.githubusercontent.com/306080/83137208-72b13500-a0f1-11ea-9e39-f26c560eab91.png)

**Comment by roma84** [comment]
This will move header to page top: 75a7223de98d7f741e9de4e696708085fb8d09c2
