### ISSUE TITLE
Use theme editor on cusom themes

### ISSUE THREAD

**Issue by dimdimich** [swissup/module-theme-editor#7]
Please let me know if we can allow some our customers to use theme editor for custom themes

**Comment by vovayatsyuk** [comment]
Header builder: https://github.com/swissup/module-theme-editor/commit/28a5ba12400db1274427a296d270e458cd5d4812

**Comment by vovayatsyuk** [comment]
http://docs.swissuplabs.com/m2/argento/customization/custom-theme/#enable-theme-editor-for-custom-theme
